title: HTML, CSS, and Javascript for Web Developers
description: Repository "HTML, CSS, and Javascript for Web Developers" Coursera.org Course Assignments
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
